name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: vcpkg
      run: |
        cd vcpkg
        ./bootstrap-vcpkg.sh

    - name: set-env
      uses: allenevans/set-env@v2.0.0
      with:
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Cache deps
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: |
          ${{ ANDROID_HOME }}
          ${{ github.workspace }}/vcpkg
        key: ${{ runner.os }}-deps

    - name: Cache build result
      id: cache-build-result
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/app/.cxx
          ${{ github.workspace }}/app/build
        key: ${{ runner.os }}-cxx-build

    - name: Cache build result
      id: cache-build-result
      uses: actions/cache@v3
      with:
        path: 
        key: ${{ runner.os }}-cxx-build
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Grant execute permission for build.sh
      run: chmod +x build.sh
      
    - name: Build with Gradle
      run: ./build.sh
