name: Android CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: vcpkg
      run: |
        cd vcpkg
        ./bootstrap-vcpkg.sh

    - name: set-env
      uses: allenevans/set-env@v2.0.0
      with:
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Install ndk
      if: steps.cache-ndk.outputs.cache-hit != 'true'
      run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.4.7075529"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Grant execute permission for build.sh
      run: chmod +x build.sh
      
    - name: Build with Gradle
      run: ./build.sh

    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.3.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: app/build/outputs/apk/debug/app-debug.apk
        asset_name: 'usc-app.apk'
        tag: ${{ github.ref }}