name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: friendlyanon/setup-vcpkg@v1
      with: { committish: acc3bcf76b84ae5041c86ab55fe138ae7b8255c7 }

    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Cache (NDK)
      uses: actions/cache@v2
      with:
        path: ${ANDROID_HOME}/ndk/21.4.7075529
        key: ndk-cache

    - name: Install NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install 'ndk;21.4.7075529'
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Grant execute permission for build.sh
      run: chmod +x build.sh
    - name: Build with Gradle
      run: ./build.sh
