name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: vcpkg
      run: |
        git clone https://github.com/Drewol/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
    - name: set-env
      uses: allenevans/set-env@v2.0.0
      with:
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug
